---
# Install nearcore

- hosts: servers
  tasks:
    - name: initialize working directory
      command: ./target/release/neard --home ~/.near init --chain-id shardnet --download-genesis
      args: 
        creates: ~/.near/node_key.json
        chdir: ~/nearcore/

    - name: update config.json
      get_url:
        url: https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/nearcore-deploy/shardnet/config.json
        dest: ~/.near/config.json
        force: yes

    - name: Create neard systemd service file
      template:
        src: neard.service.j2
        dest: /etc/systemd/system/neard.service
      become: yes

    - name: Start neard service
      systemd:
        name: neard
        state: started
      become: yes