---
# Start validating

- hosts: servers
  tasks:
    - name: Create scripts directory
      file:
        path: ~/scripts
        state: directory

    - name: Create logs directory
      file:
        path: ~/logs
        state: directory

    - name: Create checkscript
      template:
        src: templates/checkscript.j2
        dest: ~/scripts/checkscript.sh

    - name: Create pingscript
      template:
        src: templates/ping.j2
        dest: ~/scripts/ping.sh

    - name: Creates a ping crontab
      cron:
        name: ping staking pool
        minute: "0"
        hour: "*/2"
        user: "{{ ansible_user }}"
        job: sh /home/{{ ansible_user }}/scripts/ping.sh
        disabled: no
    
    - name: Create mailscript
      template:
        src: templates/sendmail.j2
        dest: ~/scripts/sendmail.sh

    - name: Creates a mail crontab
      cron:
        name: check journal and send mail
        minute: "0"
        hour: "*"
        user: "{{ ansible_user }}"
        job: sh /home/{{ ansible_user }}/scripts/sendmail.sh
        disabled: no

    - name: generate node keys
      command: near generate-key {{ pool_id }}
      args: 
        creates: ~/.near-credentials/{{ network }}/{{ account_id }}.{{ network }}.near.json

    - name: create validator_key.json
      copy:
        src: ~/.near-credentials/{{ network }}/{{ account_id }}.{{ network }}.near.json
        dest: ~/.near/validator_key.json
        remote_src: yes
        force: no
      register: validator_key_created

    - name: replace private_key string
      replace:
        path: ~/.near/validator_key.json
        regexp: 'private_key'
        replace: 'secret_key'
      when: validator_key_created.changed

    - name: replace account_id string
      replace:
        path: ~/.near/validator_key.json
        regexp: '{{ account_id }}.{{ network }}.near'
        replace: '{{ pool_id }}.factory.{{ network }}.near'
      when: validator_key_created.changed

    - name: Restart neard service
      systemd:
        name: neard
        state: restarted
      become: yes
      when: validator_key_created.changed