---
# Start validating

- hosts: backup
  tasks:
    - name: Disable ping crontab
      cron:
        name: ping staking pool
        minute: "0"
        hour: "*/2"
        user: "{{ ansible_user }}"
        job: sh /home/{{ ansible_user }}/scripts/ping.sh
        disabled: yes
    
    - name: Disable mail crontab
      cron:
        name: check journal and send mail
        minute: "0"
        hour: "*"
        user: "{{ ansible_user }}"
        job: sh /home/{{ ansible_user }}/scripts/sendmail.sh
        disabled: yes

    - name: backup validator_key.json
      copy:
        src: ~/.near/validator_key.json
        dest: ~/validator_key.json.backup.{{ ansible_date_time.iso8601 }}
        remote_src: yes
        force: yes

    - name: delete validator_key.json
      file:
        path: ~/.near/validator_key.json 
        state: absent

    - name: Restart neard service
      systemd:
        name: neard
        state: restarted
      become: yes